steps:
  # Debug step (list files first)
  - name: "alpine"
    id: "debug-list-files"
    args: ["sh", "-c", "ls -la /workspace && ls -la /workspace/server"]

  # Precheck: Fail early if no Dockerfile exists
  - name: "alpine"
    id: "check-dockerfile"
    args:
      [
        "sh",
        "-c",
        "if [ ! -f server/Dockerfile ]; then echo '❌ Missing server/Dockerfile'; exit 1; fi",
      ]

  # 1. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "docker-build"
    dir: "server"
    args: [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/souschef-api",
        ".", # Context is inside server
      ]

  # 2. Push Docker image to GCR
  - name: "gcr.io/cloud-builders/docker"
    id: "docker-push"
    args: ["push", "gcr.io/$PROJECT_ID/souschef-api"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy-cloud-run"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "souschef-api",
        "--image",
        "gcr.io/$PROJECT_ID/souschef-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--port",
        "8080",
        "--service-account",
        "souschef-api@$PROJECT_ID.iam.gserviceaccount.com",
        "--set-secrets",
        "GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_CALLBACK_URL=GOOGLE_CALLBACK_URL:latest,SESSION_SECRET=SESSION_SECRET:latest,CLIENT_URL=CLIENT_URL:latest,API_KEY=API_KEY:latest",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/souschef-api"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
